// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI0Z0b3xb2OLeFaRj6xCdFhpVCgM1DFdM',
    appId: '1:238194152930:web:6fc6dcaabba75ee4c8d5bb',
    messagingSenderId: '238194152930',
    projectId: 'flutter-e-book-app',
    authDomain: 'flutter-e-book-app.firebaseapp.com',
    databaseURL: 'https://flutter-e-book-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-book-app.appspot.com',
    measurementId: 'G-C86Z1LKRQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1txEoEbdJT46zdmCQX558NhC5nlI-9M',
    appId: '1:238194152930:android:61d2ad826f482a30c8d5bb',
    messagingSenderId: '238194152930',
    projectId: 'flutter-e-book-app',
    databaseURL: 'https://flutter-e-book-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-book-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPuS1Xc-BgnTwNfZQ3uT8GIs7SL_uEDY',
    appId: '1:238194152930:ios:6412ea8f249287b8c8d5bb',
    messagingSenderId: '238194152930',
    projectId: 'flutter-e-book-app',
    databaseURL: 'https://flutter-e-book-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-book-app.appspot.com',
    androidClientId: '238194152930-ojnlvmrapd3abhd1marldd6le358uhus.apps.googleusercontent.com',
    iosClientId: '238194152930-14956329vd8asa0agb0msvakqdfi066g.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPuS1Xc-BgnTwNfZQ3uT8GIs7SL_uEDY',
    appId: '1:238194152930:ios:402e51f1342119f6c8d5bb',
    messagingSenderId: '238194152930',
    projectId: 'flutter-e-book-app',
    databaseURL: 'https://flutter-e-book-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-book-app.appspot.com',
    androidClientId: '238194152930-ojnlvmrapd3abhd1marldd6le358uhus.apps.googleusercontent.com',
    iosClientId: '238194152930-tr14t2tlcebfvsstkmtkagnaajr9q7mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBookApp.RunnerTests',
  );
}
